# config files needs to be something like this, but named config.yml
player: pedro
notification:
  message: 'BIRL'
scale: 0.5
screen:
  gold:        [67, 100, 132, 22]
  elixir:      [67, 140, 132, 22]
  dark_elixir: [67, 180, 132, 22]
  next_button: [1230, 550]
clash:
  loot:
    pedro:       'gold > 800000 and elixir > 800000'
    rusharlison: 'gold > 600000 and elixir > 600000'
    pimento:     'gold > 500000 and elixir > 500000'
